import type { Metadata, Viewport } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { I18nProvider } from "@/lib/i18n";

// Prefix static asset URLs with the deployment basePath (empty in local dev).
// The web manifest is generated by src/app/manifest.ts and linked automatically.
const bp = process.env.NEXT_PUBLIC_BASE_PATH || "";

export const metadata: Metadata = {
  title: "Fund Watch — ดูข้อมูลกองทุนรวม",
  description:
    "ดู NAV กราฟผลการดำเนินงาน และประวัติการจ่ายปันผลของกองทุน BKD, BSIRICG และ B-CHINE-EQ",
  applicationName: "Fund Watch",
  appleWebApp: {
    capable: true,
    statusBarStyle: "default",
    title: "Fund Watch",
  },
  icons: {
    icon: `${bp}/icons/icon-192.png`,
    apple: `${bp}/icons/apple-touch-icon.png`,
  },
};

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#10b981" },
    { media: "(prefers-color-scheme: dark)", color: "#0f172a" },
  ],
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th" suppressHydrationWarning>
      <body className="min-h-screen bg-background antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <I18nProvider>{children}</I18nProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
